#!/usr/bin/perl
#
# merges entries generated by extract-host.pl
#

use warnings;
use strict;

$| = 1;

my %urls;

while(<>) {
  my @line = split;
  next unless @line == 2;
  my($url, $pri) = @line;
  $urls{$url} += $pri;
}

foreach my $key (sort {$urls{$b} <=> $urls{$a}} keys %urls) {
  print "$key\t$urls{$key}\n"
}
